#

dhcp_packages: dhcp-server
dhcp_service_name: dhcpd

dhcp_subnets:
  - subnet: 192.168.11.0
    netmask: 255.255.255.0
    dns_servers: 192.168.11.61
    range_min: 192.168.11.100
    range_max: 192.168.11.150
    broadcast_address: 192.168.11.255
    default_lease_time: 60
    max_lease_time: 720
    gateway: '192.168.11.61'
    domain_name: 'home.lab'

#domain: "home.lab"
#dhcp_hostname: "dnsserver"

dhcp_config_files:
  - template_file: dhcpd.conf.j2
    config_file: /etc/dhcp/dhcpd.conf

#
dhcpd_records:
  - hostname: proxy
    host_ip: 192.168.11.51
    mac: 00:0C:29:D1:28:3F
  - hostname: ovirt
    host_ip: 192.168.11.70
    mac: 56:31:86:12:6A:A2
  - hostname: okd4-bootstrap
    host_ip: 192.168.11.66
    mac: E2:4A:80:08:64:56
  - hostname: okd4-control-plane-1
    host_ip: 192.168.11.111
    mac: F6:54:11:8C:FE:DF
  - hostname: okd4-control-plane-2
    host_ip: 192.168.11.112
    mac: C6:49:91:97:A6:5C
  - hostname: okd4-control-plane-3
    host_ip: 192.168.11.113
    mac: 7A:3B:EC:CF:6D:D5
  - hostname: okd4-compute-1
    host_ip: 192.168.11.121
    mac: F2:2B:84:2B:CB:28
  - hostname: postgres
    host_ip: 192.168.11.62
    mac: 4A:84:DA:FE:43:C4
    