#

dhcp_packages: dhcp-server
dhcp_service_name: dhcpd

dhcp_subnets:
  - subnet: 192.168.11.0
    netmask: 255.255.255.0
    dns_servers: 192.168.11.61
    range_min: 192.168.11.100
    range_max: 192.168.11.150
    broadcast_address: 192.168.11.255
    default_lease_time: 60
    max_lease_time: 720
    gateway: '192.168.11.61'
    domain_name: 'home.lab'

#domain: "home.lab"
#dhcp_hostname: "dnsserver"

dhcp_config_files:
  - template_file: dhcpd.conf.j2
    config_file: /etc/dhcp/dhcpd.conf

#
dhcpd_records:
  - hostname: proxy
    host_ip: 192.168.11.51
    mac: 00:0C:29:D1:28:3F
  - hostname: bootstrap
    host_ip: 192.168.11.66
    mac: E2:4A:80:08:64:56
  - hostname: master1
    host_ip: 192.168.11.121
    mac: 22:63:8E:FB:5C:08
  - hostname: master2
    host_ip: 192.168.11.122
    mac: 46:F9:A5:28:B0:E4
  - hostname: master3
    host_ip: 192.168.11.123
    mac: A6:A4:C3:C7:8F:9E
  - hostname: worker1
    host_ip: 192.168.11.124
    mac: 56:C2:AC:BD:1D:89
  - hostname: worker2
    host_ip: 192.168.11.125
    mac: 5E:20:EF:D2:34:FB
  - hostname: postgres
    host_ip: 192.168.11.62
    mac: 4A:84:DA:FE:43:C4
  - hostname: kube-master1
    host_ip: 192.168.11.71
    mac: 16:09:B8:3D:E3:D2
  - hostname: kube-master2
    host_ip: 192.168.11.72
    mac: D2:F8:E2:81:36:3E
  - hostname: kube-worker1
    host_ip: 192.168.11.73
    mac: 72:1D:3E:80:B6:4E
  - hostname: kube-worker2
    host_ip: 192.168.11.74
    mac: 9E:00:CF:48:6C:92
  - hostname: podman
    host_ip: 192.168.11.63
    mac: D6:B4:C7:5B:43:2B
    