#
# Preperation section

ansible-managed: "This file is managed by Ansible"

dns_packages: [bind, bind-utils]
dns_service_name: named

subnets:
  - subnet: "192.168.11.0/24"

listening_ips:
  - ip: 127.0.0.1
  - ip: 192.168.11.61

domain: "home.lab"
dns_hostname: "dnsserver"

dns_config_files:
  - template_file: named.conf.j2
    config_file: /etc/named.conf
  - template_file: named.homelab.conf.j2
    config_file: /etc/named/named.homelab.conf   
#  - template_file: home.lab.zone.j2
#    config_file: /var/named/home.lab.zone
#  - template_file: 192.168.10.zone.j2
#    config_file: /var/named/192.168.10.zone
  - template_file: okd4.home.lab.zone.j2
    config_file: /var/named/okd4.home.lab.zone
  - template_file: reverse.okd4.home.lab.zone.j2
    config_file: /var/named/reverse.okd4.home.lab.zone    

## It is not recommended to use "_". Use "-"
dns_records:
  - hostname: dnsserver
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: workstation
    host_ip: 192.168.11.10
    ip_last_oct: 10


service_nodes:
  - hostname: proxy
    host_ip: 192.168.11.51
    ip_last_oct: 51
  - hostname: postgresdb
    host_ip: 192.168.11.62
    ip_last_oct: 62
  - hostname: ovirt.okd4
    host_ip: 192.168.11.70
    ip_last_oct: 70
  - hostname: dns
    host_ip: 192.168.11.61
    ip_last_oct: 61    
  - hostname: dnsserver.okd4
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: api.okd4
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: api-int.okd4
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: '*.apps.okd4'
    host_ip: 192.168.11.61
    ip_last_oct: ;61
  - hostname: oauth-openshift.okd4
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: console-openshift-console.okd4
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: okd4-services.okd4
    host_ip: 192.168.11.61
    ip_last_oct: 61

bootstrap_nodes:
  - hostname: okd4-bootstrap.okd4
    host_ip: 192.168.11.66
    ip_last_oct: 66

master_nodes:
  - hostname: okd4-control-plane-1.okd4
    host_ip: 192.168.11.111
    ip_last_oct: 111
  - hostname: okd4-control-plane-2.okd4
    host_ip: 192.168.11.112
    ip_last_oct: 112
  - hostname: okd4-control-plane-3.okd4
    host_ip: 192.168.11.113
    ip_last_oct: 113

compute_nodes:
  - hostname: okd4-compute-1.okd4
    host_ip: 192.168.11.121
    ip_last_oct: 121

etcd_nodes:
  - hostname: etcd-1.okd4
    host_ip: 192.168.11.111
    ip_last_oct: 111
  - hostname: etcd-2.okd4
    host_ip: 192.168.11.112
    ip_last_oct: 112
  - hostname: etcd-3.okd4
    host_ip: 192.168.11.113
    ip_last_oct: 113
