#
# Preperation section

ansible-managed: "This file is managed by Ansible"

dns_packages: [bind, bind-utils]
dns_service_name: named

subnets:
  - subnet: "192.168.11.0/24"

listening_ips:
  - ip: 127.0.0.1
  - ip: 192.168.11.61

domain: "home.lab"
dns_hostname: "dnsserver"
ocp_suff: "ocp"

dns_config_files:
  - template_file: named.conf.j2
    config_file: /etc/named.conf
  - template_file: named.homelab.conf.j2
    config_file: /etc/named/named.homelab.conf   
#  - template_file: home.lab.zone.j2
#    config_file: /var/named/home.lab.zone
#  - template_file: 192.168.10.zone.j2
#    config_file: /var/named/192.168.10.zone
  - template_file: ocp.home.lab.zone.j2
    config_file: /var/named/ocp.home.lab.zone
  - template_file: reverse.ocp.home.lab.zone.j2
    config_file: /var/named/reverse.ocp.home.lab.zone    

## It is not recommended to use "_". Use "-"
dns_records:
  - hostname: dnsserver
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: workstation
    host_ip: 192.168.11.10
    ip_last_oct: 10


service_nodes:
  - hostname: proxy
    host_ip: 192.168.11.51
    ip_last_oct: 51
  - hostname: postgresdb
    host_ip: 192.168.11.62
    ip_last_oct: 62
  - hostname: podman.ocp
    host_ip: 192.168.11.63
    ip_last_oct: 63
  - hostname: registry.ocp
    host_ip: 192.168.11.63
    ip_last_oct: 63    
  - hostname: ovirt.ocp
    host_ip: 192.168.11.70
    ip_last_oct: 70
  - hostname: dns
    host_ip: 192.168.11.61
    ip_last_oct: 61    
  - hostname: dnsserver.ocp
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: api.ocp
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: oauth-openshift.apps
    host_ip: 192.168.11.61
    ip_last_oct: 61    
  - hostname: api-int.ocp
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: '*.apps.ocp'
    host_ip: 192.168.11.61
    ip_last_oct: ;61
  - hostname: oauth-openshift.ocp
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: console-openshift-console.ocp
    host_ip: 192.168.11.61
    ip_last_oct: 61
  - hostname: ocp-services.ocp
    host_ip: 192.168.11.61
    ip_last_oct: 61

bootstrap_nodes:
  - hostname: bootstrap.ocp
    host_ip: 192.168.11.66
    ip_last_oct: 66

master_nodes:
  - hostname: master1.ocp
    host_ip: 192.168.11.121
    ip_last_oct: 121
  - hostname: master2.ocp
    host_ip: 192.168.11.122
    ip_last_oct: 122
#  - hostname: master3.ocp
#    host_ip: 192.168.11.123
#    ip_last_oct: 123

compute_nodes:
  - hostname: worker1.ocp
    host_ip: 192.168.11.124
    ip_last_oct: 124
  - hostname: worker2.ocp
    host_ip: 192.168.11.125
    ip_last_oct: 125

kubernetes_master_nodes:
  - hostname: kube-master1.ocp
    host_ip: 192.168.11.71
    ip_last_oct: 71
  - hostname: kube-master2.ocp
    host_ip: 192.168.11.72
    ip_last_oct: 72

kubernetes_worker_nodes:
  - hostname: kube-worker1.ocp
    host_ip: 192.168.11.73
    ip_last_oct: 73
  - hostname: kube-worker2.ocp
    host_ip: 192.168.11.74
    ip_last_oct: 74


#etcd_nodes:
#  - hostname: etcd-1.ocp
#    host_ip: 192.168.11.121
#    ip_last_oct: 121
#  - hostname: etcd-2.ocp
#    host_ip: 192.168.11.122
#    ip_last_oct: 122
#  - hostname: etcd-3.ocp
#    host_ip: 192.168.11.123
#    ip_last_oct: 123
