#

dhcp_packages: dhcp-server
dhcp_service_name: dhcpd

dhcp_subnets:
  - subnet: 192.168.11.0
    netmask: 255.255.255.0
    dns_servers: 192.168.11.50
    range_min: 192.168.11.50
    range_max: 192.168.11.100
    broadcast_address: 192.168.11.255
    default_lease_time: 60
    max_lease_time: 720
    gateway: '192.168.11.50'
    domain_name: 'home.lab'

#domain: "home.lab"
#dhcp_hostname: "dnsserver"

dhcp_config_files:
  - template_file: dhcpd.conf.j2
    config_file: /etc/dhcp/dhcpd.conf

#
dhcpd_records:
  - hostname: proxy
    host_ip: 192.168.11.51
    mac: 00:0C:29:D1:28:3F
  - hostname: atest
    host_ip: 192.168.11.78
    mac: 00:0C:29:7F:36:DE
  - hostname: okd4-bootstrap
    host_ip: 192.168.11.52
    mac: 00:50:56:36:8B:8D
  - hostname: okd4-control-plane-1
    host_ip: 192.168.11.53
    mac: 00:50:56:28:FC:7D
#  - hostname: etcd-1
#    host_ip: 192.168.11.53
#    mac: 00:50:56:28:FC:7D
  - hostname: okd4-control-plane-2
    host_ip: 192.168.11.54
    mac: 00:50:56:34:29:55
#  - hostname: etcd-2
#    host_ip: 192.168.11.54
#    mac: 00:50:56:34:29:55
  - hostname: okd4-control-plane-3
    host_ip: 192.168.11.55
    mac: 00:50:56:28:4F:8B
#  - hostname: etcd-3
#    host_ip: 192.168.11.55
#    mac: 00:50:56:28:4F:8B
  - hostname: okd4-compute-1
    host_ip: 192.168.11.56
    mac: 00:50:56:3F:47:CF
