---

- block:
  - include: http_configure.yml
    loop: "{{ http_sites }}"

  - include: http_configure.yml
    loop: "{{ https_sites }}"
    when: https_sites is defined
#
  - include: https_configure.yml
#    loop: "{{ https_sites }}"
    when: 
      - https_sites is defined 
      - item.state == "present"
    loop: "{{ https_sites }}"

  become: true

